### ISSUE TITLE
stroke-dashoffset svg animation

### ISSUE THREAD

**Issue by riki81** [Keyframes/jQuery.Keyframes#45]
Hi, I've tried to use your script with the "stroke-dashoffset" to animate an SVG.
This is the used code:
```
$.keyframe.define({
   name: data_name,
   to: {
      'stroke-dashoffset': stroke_dashoffset
   },
});
```

This code is working well on Firefox and Chrome, but nothing from Safari.

The code that should be generated is sth like this:
```
@-webkit-keyframes data_name {
  to {
    stroke-dashoffset: 160;
  }
}

@keyframes data_name {
  to {
    stroke-dashoffset: 160;
  }
}
```

PS: I am using your minified version, to be sure "PrefixFree" is included.

What's wrong?!

**Comment by krazyjakee** [comment]
This is a CSS issue not an issue with jqk. You'd be better off posting this to stackoverflow or reddit.
