### ISSUE TITLE
Can we & how to deliberately omit Prefix free from jQuery Keyframes?

### ISSUE THREAD

**Issue by milosdjakonovic** [Keyframes/jQuery.Keyframes#51]
While being usable, Prefix Free includes many sides effects like doubling http requests of css resources, and there are situations where I would rather prefix css declarations inside media query manually.

I can see *only usage* of PF at line 58 `css = PrefixFree.prefixCSS(css + "}");` - can I just replace it with

`css += "}";`

and solve problem this way?

**Comment by krazyjakee** [comment]
Yup! It's not a problem.

We could potentially add a conditional into the master branch to ignore prefixfree if it's not been loaded.

**Comment by milosdjakonovic** [comment]
I've just taught so, like:

`
if(window.PrefixFree) css = PrefixFree.prefixCSS(css + "}");
`
