### ISSUE TITLE
Doesn't work on Safari 

### ISSUE THREAD

**Issue by BQRA** [Keyframes/jQuery.Keyframes#55]
Hi, is jQuery.Keyframes working on Safari? Because i couldn't. It seems to put some code in <head> tag like <style>@-keyframes...</style>, but Safari might be read <style>@-webkit-keyframes...</style>.
What should i do for using this plugin on Safari?

**Comment by milosdjakonovic** [comment]
jQuery.Keyframes should work on any css animation capable browser (you can test feature support with tool like `Modernizr`). Which browser version are you using? I think css animations is supported on Safari from version 5.1...

**Comment by BQRA** [comment]
Solved for me;
First reason, jquery path not found in examples/index.html <head>,
second reason, there is no using like **delay: 1**. It should be **delay: "1s"** in examples/index.html 
third reason, i used $(document).ready instead of $(window).load
