### ISSUE TITLE
translateX not working in animation

### ISSUE THREAD

**Issue by joeypunkrock** [Keyframes/jQuery.Keyframes#57]
Thanks for this great plugin! One issue I have is with translateX not moving the element.

I have for define:

```
		$.keyframe.define([{
		    name: 'rotate',
		    from: {
		        'transform' : 'rotate(0deg)',
		        'transform' : 'translateX(20vw)',
		        'transform' : 'rotate(0deg)',
		        'z-index' : '1'
		    },
		    to: {
		        'transform' : 'rotate(360deg)',
		        'transform' : 'translateX(20vw)',
		        'transform' : 'rotate(-360deg)',
		        'z-index' : '2'
		    }
		    }
		]);

```

and then I am playing the keyframe as:

```
moon.playKeyframe({
		    name: 'rotate', // name of the keyframe you want to bind to the selected element
		    duration: '10s', // [optional, default: 0, in ms] how long you want it to last in milliseconds
		    timingFunction: 'linear', // [optional, default: ease] specifies the speed curve of the animation
		    delay: '0s', //[optional, default: 0s]  how long you want to wait before the animation starts
		    iterationCount: 'infinite', //[optional, default:1]  how many times you want the animation to repeat
		    direction: 'normal', //[optional, default: 'normal']  which direction you want the frames to flow
		    fillMode: 'forwards', //[optional, default: 'forward']  how to apply the styles outside the animation time, default value is forwards
		    complete: function(){} //[optional] Function fired after the animation is complete. If repeat is infinite, the function will be fired every time the animation is restarted.
		});

```

with moon... i have made sure to assign it to the object: `var moon = $('#moon');`

The animation works fine as the object spins, but it does not translateX, just sits where the object is loaded.

No errors in the log I see:

rotate @keyframes rotate {from {transform:rotate(0deg);z-index:1;}to {transform:rotate(-360deg);z-index:2;}}

Style Applied: rotate 10s linear 0s infinite normal forwards
Rendered Style: rotate 10s linear 0s infinite normal forwards running

When I do the same keyframe as standard CSS it works and translates, but not with the plugin...

Thank you for your time! If I am not clear enough please let me know.

**Comment by MichaelBarb** [comment]
I had similar issues at one time.  jQuery.Keyframes uses an addin to make it less sensitive to the browser being used.  Notice I used the word "less".  It works most of the time but not always.  There were times I had to explicitly duplicate the commands.  Once with out and prefix and once with the webkit prefix.
I am not saying this is your problem but it looks similar to one that I had.

**Comment by milosdjakonovic** [comment]
@joeypunkrock in what browsers does this happen?

**Comment by krazyjakee** [comment]
I'm very sure it's because there are multiple transforms. Like the CSS standard, you must merge all transforms into one.

```javascript
$.keyframe.define([{
            name: 'rotate',
            from: {
                'transform' : 'rotate(0deg) translateX(20vw) rotate(0deg)',
                'z-index' : '1'
            },
            to: {
                'transform' : 'rotate(360deg) translateX(20vw) rotate(-360deg)',
                'z-index' : '2'
            }
            }
        ]);
```

**Comment by milosdjakonovic** [comment]
I admit, I've just asked for pen, without reviewing presented code :sleeping: 

Not only multiple transform functions are impossible in such manner of declaration, but even if you declare them the way @krazyjakee did, your gonna meet:

https://css-tricks.com/debugging-css-keyframe-animations/ (The Pains of Multiple Transform Values)

for solution, generate matrix/matrix3d function:
https://gist.github.com/milosdjakonovic/66a8861cd26e6cd707d6

**Comment by MichaelBarb** [comment]
This was almost a year ago.  I was working with Internet Explorer, Edge, and 
Chrome.  I suspect it was webkit.  This was my class project.  Check out the following link.
http://net4.ccs.neu.edu/home/barbm/myProject/myProject.aspx

Note: I noticed some things work differently than they did a year ago.  A year ago the CSS and WebGL version worked nearly identical.  Now I noticed the angles are opposite in the CSS version.

**Comment by joeypunkrock** [comment]
Now I feel like a fool. I would blame it on lack of sleep but nope, I just have a lot to learn.

@krazyjakee Your solution works perfectly. I should have really thought about doing it that way. I wonder if there is a way to target one of the transforms selectors specifically, like translateX(20vw) inside a function and edit the value for the keyframe when the function is ran... or would assigning a new keyframe with a different translateX to the object (moon) be the only way around that?

@milosdjakonovic Thank you for the articles, I didn't realise such a problem would occur with multiple transforms. These will be very helpful.

@MichaelBarb Thank you for the help, I believe your project may be of some help to me in understanding more about animations.
