### ISSUE TITLE
Animation Sequences in Chrome

### ISSUE THREAD

**Issue by peterbbc** [Keyframes/jQuery.Keyframes#59]
Having an issue in Chrome where running animations in a sequence causes some of the animations to fire a second time. I've traced it back to the events coming out of Chrome.
Code example:

```
$.keyframe.define([{
    name: 'showHeadline',
    '0%': {'top': '150px', 'opacity':'0'},
    '100%': {'top': '0', 'opacity':'1'}
}]);

$.keyframe.define([{
    name: 'hideHeadline',
    '0%': {'top': '0', 'opacity':'1'},
    '100%': {'top': '150px', 'opacity':'0'}
}]);

$.keyframe.define([{
    name: 'showSummary',
    '0%': {'top': '150px', 'opacity':'0'},
    '100%': {'top': '95px', 'opacity':'1'}
}]);

$.keyframe.define([{
    name: 'hideSummary',
    '0%': {'top': '95px', 'opacity':'1'},
    '100%': {'top': '150px', 'opacity':'0'}
}]);

$('#summary').playKeyframe({
    name: 'hideSummary',
    duration: '750ms',
    timingFunction: 'cubic-bezier(0.600, -0.280, 0.735, 0.045)',
    complete: function(){

        $('#headline').playKeyframe({
            name: 'hideHeadline',
            duration: '750ms',
            timingFunction: 'cubic-bezier(0.600, -0.280, 0.735, 0.045)',
            complete: function(){       

                $('#headline').html(newHeadline);
                $('#summary').html(newSummary);

                $('#headline').playKeyframe({
                    name: 'showHeadline',
                    duration: '750ms',
                    timingFunction: 'cubic-bezier(0.175, 0.885, 0.320, 1.275)',
                    complete: function(){

                        $('#summary').playKeyframe({
                            name: 'showSummary',
                            duration: '750ms',
                            timingFunction: 'cubic-bezier(0.175, 0.885, 0.320, 1.275)'
                        })
                    }
                })
            }
        })
    }
});
```

Running this causes the animations to run as you would expect with `animationend` events firing at the end of each one.
However when all four animations have run a `webkitAnimationEnd` event is fired on the first animation, this causes the three subsequent animations to run again (with `animationend` events firing after each one).
So you effectively get the animations running as: 1 - 2 - 3 - 4 - 2 - 3 - 4

The only workarounds I've been able to find is either changing the `_prefixEvent` function to use `.one()` instead of `.on()` but this breaks callbacks for iterative animations. Or remove all the prefixes (which isn't ideal on a compatibility front).
Attempting to call `.off()` inside the event doesn't work.
The other alternative of course is to put appropriate delays on each animation so they run in sequence but that seems like a slightly backwards way of doing it.

Whilst in my use case I can tweak the library to do what I need I feel like such a fantastic library shouldn't need to put up with strange browser behaviour! 😄

**Comment by krazyjakee** [comment]
Any chance this could be revisited with a codepen?
