### ISSUE TITLE
Files not found does this still work?

### ISSUE THREAD

**Issue by BrendanJackson** [Keyframes/jQuery.Keyframes#60]
Failed to load resource: the server responded with a status of 404 (Not Found)
http://code.jquery.com/jquery-0.0.9.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
javascript.js:13 Uncaught SyntaxError: Unexpected token -
http://localhost/assets/js/jquery.keyframes.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://code.jquery.com/jquery-0.0.9.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

I tried using the CDN as well but when I use the supportedFlag I still get a false evaluation, my IDE highlights the files red even in the demo. Is this broken or is there just something I am missing?

**Comment by krazyjakee** [comment]
you're using the keyframes version on the jquery cdn.
