### ISSUE TITLE
'this' keyword not working

### ISSUE THREAD

**Issue by TechMky** [Keyframes/jQuery.Keyframes#64]
I hope that I am wrong but take a look at the code below:
```
$('#animate').playKeyframe({
            name: 'flipInX',
            duration: '1s',
            fillMode: 'both',
            complete: () =>{
                $(this).resetKeyframe(() => console.log('reset'));
            }
        });
```
The "**complete**" function does not work until I replace the '**this**' keyword with '**#animate**'. Is this supposed to happen?
I assumed that '**this**' would already have reference to '**#animate**'

**Comment by krazyjakee** [comment]
This will help you understand `this` in the context: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Save $('#animate') to a variable and reference that instead.
