### ISSUE TITLE
Removing unused keyframes

### ISSUE THREAD

**Issue by brettdewoody** [Keyframes/jQuery.Keyframes#66]
I'm building a prototype where I'm creating a lot of dynamic keyframes with:

    $.keyframe.define([{
        name: `rotate_${var1}_${var2}`,
        ...
    }]);

where `var1` and `var2` could be a combination of values, resulting an potentially thousands of keyframes being defined. 

Is there any harm in defining so many keyframes? And if so, is there a method to remove keyframes.

**Comment by krazyjakee** [comment]
There's no harm.
