### ISSUE TITLE
jquery.keyframes.min.js is different to jquery.keyframes.js

### ISSUE THREAD

**Issue by mbrammer** [Keyframes/jQuery.Keyframes#67]
Hi,

I just figured out that the code of jquery.keyframes.**min**.js is different to jquery.keyframes.js.
In the not minified version is the StyleFix and PrefixFree lib missing.
It seems one of the files is outdated.

Another thing I noticed, is that the version with StyleFix/PrefixFree is loading my CSS files three times, because of the CSS prefixing. This leads into flickering issues in Firefox because auf the prefixing.
I switched to the version without StyleFix/PrefixFree and now everything is fine.

**Comment by krazyjakee** [comment]
fixed!
