### ISSUE TITLE
Use a style as a keyframe and pull a style from a keyframe

### ISSUE THREAD

**Issue by Ma-XX-oN** [Keyframes/jQuery.Keyframes#71]
Is there a way to pull a style from a keyframe and make it into a CSS style?  How about pulling a style out of the stylesheet and adding it as a keyframe?

It would be great if I don't have to specify these two things in two different areas and just share the information.  In this way, I could specify it only once.

My usecase is to use javascript to set a tag's class such that it will invoke the beginning of an animation keyframe sequence, the end of an animation keyframe sequence, or allow the entire keyframe sequence to run.

Alternatively, if there was some other way to use your code to do this, then that would be fine too. 😄

**Comment by krazyjakee** [comment]
Can you throw up your use case onto a codepen or jsfiddle? I can take a look and see what can be done.
