### ISSUE TITLE
IndexSizeError in Internet Explorer 11

### ISSUE THREAD

**Issue by justferfernandez** [Keyframes/jQuery.Keyframes#72]
The jQuery.jeyframes.min.js throws an IndexSizeError when running in IE11. Is this a known issue or am I the only one experiencing this.

**Comment by justferfernandez** [comment]
it seems to occur here:
`var ruleIndex = Keyframes.sheet.insertRule(css);`

**Comment by krazyjakee** [comment]
@justferfernandez any chance you could produce an example on codepen or jsfiddle? I would really appreciate it.

**Comment by justferfernandez** [comment]
Hi! I'm just checking back if there's anything new here. :) Thank you!

**Comment by hrisi87** [comment]
Hi, I have the same problem with IE11 IndexSizeError. I'm using jquery 3.3.1 and seems it has a problem with jquery SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.
SCRIPT5022: IndexSizeError
jquery-3.3.1.min.js (3827,3)
SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

**Comment by hrisi87** [comment]
> Hi! I'm just checking back if there's anything new here. :) Thank you!

Hi, I used this script https://raw.githubusercontent.com/Keyframes/jQuery.Keyframes/ie1011fix/jquery.keyframes.js and for me is working on ie 11

**Comment by justferfernandez** [comment]
Thanks! This really helps! :D

**Comment by su-ex** [comment]
Well, I investigated a bit.
There are two things that need to be done to get this running in Internet Explorer 10 and 11:

1. Some polyfill for Object.assign(), see:
    - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill
    - since this is using babel maybe add it this way: https://stackoverflow.com/questions/44244468/method-assign-not-supported-in-ie-what-to-do
    - or this way: https://www.npmjs.com/package/es6-object-assign
2. insertRule requires adding index although it's optional per specification (see: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule#Syntax), so just replace
var ruleIndex = Keyframes.sheet.insertRule(css);
with 0 as default value for index so it becomes
var ruleIndex = Keyframes.sheet.insertRule(css, 0);
in the generate function.

These two things need to be done in the other repo.

@krazyjakee Should I create some pull request or are you against polyfills or how to get this into here for the benefit of others?

**Comment by krazyjakee** [comment]
Sorry for the lurking, life is majorly in the way right now. I am not against a polyfill and would follow up with any pull request. Thanks.

**Comment by su-ex** [comment]
This solved it as far as I can see: https://github.com/Keyframes/Keyframes/pull/4/commits/c1fea19c910b178687bd0bfd91b6e0175fde42dd

**Comment by krazyjakee** [comment]
@su-ex quick question, why `es6-object-assign/auto` over `@babel/plugin-transform-object-assign`?

**Comment by su-ex** [comment]
Because I didn't get it to run with babel in the final dist version of jQuery.Keyframes (it always used the src probably on include, even if I added the babel in this repo and built it). The dist version of the Keyframes core were ok with it.

**Comment by krazyjakee** [comment]
@su-ex ok, nice catch!

**Comment by su-ex** [comment]
Yeah, finally, after two days I finally got my websites running in an acceptable way in Internet Explorer, too. -.-

**Comment by krazyjakee** [comment]
Ok, this is deployed in 1.0.6 https://www.npmjs.com/package/jquerykeyframes

Please let me know if this has solved this issue and we can close it.

**Comment by su-ex** [comment]
Tested with the deployed version and seems working.

**Comment by krazyjakee** [comment]
awesome!
