### ISSUE TITLE
Module Import Config Problem

### ISSUE THREAD

**Issue by moosetunes** [Keyframes/jQuery.Keyframes#81]
All:
Initial install of plugin.  @keyframes/core and jquery modules installed via npm.   Based on example, the following header scripts were inserted:

<script type="text/javascript" src='/node_modules/@keyframes/core/dist/jquery.keyframes.js'></script>
<script type="text/javascript" src="/node_modules/jquery/dist/jquery.js"></script>

I'm getting a single  error which is derived from jquery.keyframes.js line:
import Keyframes from '@keyframes/core';

"Uncaught SyntaxError: Cannot use import statement outside a module"

I've tried various paths for the import statement but the error persists.

Thoughts?
Thanks in advance.
Steve

**Comment by krazyjakee** [comment]
Use the example provided to know what script tags to add: https://github.com/Keyframes/jQuery.Keyframes/blob/master/example/index.html
